" Awesome Vim Configuration "
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

" theme "
:colorscheme ir_black

" faster ctrlp performance "
let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

" toggle search highlighting "
set hlsearch!
nnoremap <F2> :set hlsearch!<CR>

" display line number "
set number

" faster cycle between tabs "
nnoremap H gT
nnoremap L gt

" stop insert comment character in new line "
set formatoptions-=ro
